export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const MAID_UPDATE_SUCCESS = 'MAID_UPDATE_SUCCESS';
export const MAID_UPDATE_FAIL = 'MAID_UPDATE_FAIL';

export const MAID_CREATE_SUCCESS = 'MAID_CREATE_SUCCESS';
export const MAID_CREATE_FAIL = 'MAID_CREATE_FAIL';

export const UPDATE_PHOTO_SUCCESS = 'UPDATE_PHOTO_SUCCESS';
export const UPDATE_PHOTO_FAIL = 'UPDATE_PHOTO_FAIL';

export const MAID_ADDED_TO_LIST_SUCCESS = 'MAID_ADDED_TO_LIST_SUCCESS';
export const MAID_ADDED_TO_LIST_FAIL = 'MAID_ADDED_TO_LIST_FAIL';

export const SIGNOUT = 'SIGNOUT';